// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApprovalWarner: typeof import('./components/ApprovalWarner.vue')['default']
    Auction: typeof import('./components/Auction.vue')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    ChainWarner: typeof import('./components/ChainWarner.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    'Gg:arrowsExchangeV': typeof import('~icons/gg/arrows-exchange-v')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    'SimpleIcons:discord': typeof import('~icons/simple-icons/discord')['default']
    'SimpleIcons:opensea': typeof import('~icons/simple-icons/opensea')['default']
    'SimpleIcons:twitter': typeof import('~icons/simple-icons/twitter')['default']
    StackingInline: typeof import('./components/StackingInline.vue')['default']
    Token: typeof import('./components/Token.vue')['default']
    WalletButton: typeof import('./components/WalletButton.vue')['default']
  }
}

export { }
